@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\Raze\Documents\StormDataBase\PROJECTS\Unsheard tools\QuickVanish(MIDNIGHTCORD)\Install.exe
REM BFCPEICON=C:\Program Files (x86)\Advanced BAT to EXE Converter v4.59\ab2econv459\icons\icon12.ico
REM BFCPEICONINDEX=1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=0
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=midnight
REM BFCPEVERDESC=hyper message deleter for discord
REM BFCPEVERCOMPANY=3mk
REM BFCPEVERCOPYRIGHT=idk
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=25
REM BFCPEWINDOWWIDTH=80
REM BFCPEWTITLE=Window Title
REM BFCPEOPTIONEND
@echo off
echo installin...
pip install -r requirements.txt
pause