@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\Raze\Documents\StormDataBase\PROJECTS\Unsheard tools\QuickVanish(MIDNIGHTCORD)\MIDNIGHTCORD.exe
REM BFCPEICON=C:\Users\Raze\Documents\StormDataBase\PROJECTS\Unsheard tools\QuickVanish(MIDNIGHTCORD)\logo-icon.ico
REM BFCPEICONINDEX=1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=1
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=MIDNIGHT
REM BFCPEVERDESC=hyper message deleter
REM BFCPEVERCOMPANY=storm290
REM BFCPEVERCOPYRIGHT=Copyright Info
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=25
REM BFCPEWINDOWWIDTH=80
REM BFCPEWTITLE=MIDNIGHT CORD
REM BFCPEOPTIONEND
@echo off
echo wlc
python MIDNIGHT.py
pause